### ISSUE TITLE
Fix alt text doesn't properly write the alt text on first try

### ISSUE THREAD

**Issue by jwbowles** [ucfcdl/UDOIT#81] opened 2015-12-14 21:01 UTC
When running the U FIX IT! for missing image alt tags it doesn't seem to properly write the fix the first time. If the U FIX IT process is repeated a second time it will update properly. All other fixes seem to work the first time.

**Comment by bagofarms** [comment] 2015-12-17 20:58
I'm not able to replicate this on the latest version of UDOIT.  Could you provide more details, such as what type of content you're trying to fix (assignment, page, discussion, etc.)  and the HTML of the content?

**Comment by jwbowles** [comment] 2015-12-17 21:02
This is in a content page and the html is as follows
`<img style="float: right;" src="/courses/928782/files/35591059/preview" alt="" width="245" height="646" data-api-endpoint="https://mcccd.instructure.com/api/v1/courses/928782/files/35591059" data-api-returntype="File" />`

It does however work after performing the U Fix It the second time.

**Comment by bagofarms** [comment] 2015-12-17 21:25
I just tested that exact HTML, and was able to fix it on the first try with Chrome on Mac.  What version of UDOIT are you using?  Also, what browser and OS are you using?

**Comment by bagofarms** [comment] 2016-02-24 19:56
@jwbowles Do you have an update on my questions above?

**Comment by bagofarms** [comment] 2016-03-03 22:50
I'm going to close this issue since we were unable to reproduce it, and no further details were given.

**Closed by bagofarms** 2016-03-03 22:50 UTC
