### ISSUE TITLE
Captioned YouTube video throws error

### ISSUE THREAD

**Issue by robfentress** [ucfcdl/UDOIT#125] opened 2016-04-12 20:43 UTC
Running a scan on a YouTube video that I have captioned in YouTube returns an erroneous error "Synchronized captions should be provided for prerecorded web-based video".
 The YouTube Video tested on is can be found at https://www.youtube.com/watch?v=odNGHMgLHNE

![screen shot 2016-04-12 at 4 42 36 pm](https://cloud.githubusercontent.com/assets/9356499/14474980/a456ab6c-00cd-11e6-820e-7cfbefa63d7c.png)

**Comment by bagofarms** [comment] 2016-04-12 20:48
We're actually working on this issue right now.  We didn't realize until last week that the YouTube APIs had changed.

**Comment by bagofarms** [comment] 2016-04-12 20:48
Closing because it's a duplicate of #122

**Closed by bagofarms** 2016-04-12 20:48 UTC
Labels: duplicate

**Comment by robfentress** [comment] 2016-05-13 17:11
Still doesn't work

**Comment by bagofarms** [comment] 2016-05-13 18:02
I believe that is because the video you posted is private.  We're unable to get closed captioning data from private videos.  If you find one that is public with closed captions that is still throwing an error, please let me know.

**Comment by robfentress** [comment] 2016-05-13 20:03
The video I tried was public and captioned.
https://youtu.be/6j_eeLdpwFY

On Fri, May 13, 2016 at 2:02 PM, Jacob Bates <notifications@github.com>
wrote:

> I believe that is because the video you posted is private. We're unable to
> get closed captioning data from private videos. If you find one that is
> public with closed captions that is still throwing an error, please let me
> know.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ucfcdl/UDOIT/issues/125#issuecomment-219116517>
>



-- 
Robert Fentress
Senior Accessibility Solutions Designer
540.231.1255

Technology-enhanced Learning & Online Strategies
Assistive Technologies
1180 Torgersen Hall
620 Drillfield Drive (0434)
Blacksburg, Virginia 24061

**Comment by bagofarms** [comment] 2016-05-19 15:18
I'm not able to replicate the issue with that video on Master.  We're still digging into the code to see if we can improve the detection logic, though.
